### ISSUE TITLE
Root access doesn't work anymore on crDroid 4.4

### ISSUE THREAD

**Issue by azazel75** [crdroidandroid/android_device_motorola_harpia_old#1]
Sorry guys this isn't the right place but It wasn't clear where to report bugs.
So I'm using crDroid on this phone and after upgrading today after OTA update notification root access doesn't work anymore, even with the "Ad Away" panel in the crDroid settings. It complains that root isn't activated (instead it is under the developer tools).
I'm currently using build crDroidAndroid-8.1-20180713-harpia-v4.4.

Let me know if you need any other info.

**Comment by neobuddy89** [comment]
It is due to recent change by LOS.
This has been fixed for new builds.

Please notify your maintainer.

**Comment by azazel75** [comment]
How am I supposed to do that?

**Comment by gwolf2u** [comment]
Ask on forum or so

**Comment by neobuddy89** [comment]
@SubhrajyotiSen

**Comment by SubhrajyotiSen** [comment]
@azazel75 I will make a new build and post it on the XDA thread. You should get a OTA too when it's up.

**Comment by azazel75** [comment]
@SubhrajyotiSen  thank you. For the future, It would better if you had clearer bug reporting policies here on github, something that doesn't involve subscribing to a forum! Thanks again

**Comment by neobuddy89** [comment]
@azazel75 Well, thanks for suggestion. However, this is not our full time work. We love to work for community as a part of community. So, little reaching won't hurt anyone.
